#!/usr/bin/env python3
"""
Generate the three preview pages.

The chrome (unofficial ribbon, brand bar, the Campus Rec nav, the sub-nav across these
previews, footer) is identical on every page, so it lives here. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "pool":      "JZFbwQPBPYl4stBPd8MkF8",   # everything in the WSRC pool, a week at a time
    "fit":       "NF0VU5945BliG4dBjcG4Ye",   # Fit Lane Swim (and closures)
    "community": "jqQnktEJJFMjZallFoztFW",   # Recreation, Women's Only and 2SLGBTQIA+ swims
}

NAV = [
    ("index.html",           "Pool Schedule"),
    ("fit-lane-swim.html",   "Fit Lane Swim"),
    ("community-swims.html", "Rec &amp; Community Swims"),
]

SCHED = "https://www.uwo.ca/campusrec/schedules/index.html"


def cal(key, title, caption=""):
    token = EMBED[key]
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="cal">
    <iframe src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    ext = 'target="_blank" rel="noopener"'
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a Western University website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&family=Rubik:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a Western University page. A replica of the
  <a href="{SCHED}" {ext}>Western Campus Recreation schedules page</a>
  with live <a href="https://www.poolrelay.com" {ext}>Pool&nbsp;Relay</a> calendars.
</div>

<header class="brandbar">
  <div class="wrap inner">
    <a class="mark" href="index.html"><span class="city">WESTERN UNIVERSITY</span>Western Campus Recreation</a>
    <div class="tel">Western Student Recreation Centre &middot; London, Ontario</div>
  </div>
</header>

<nav class="main">
  <ul>
    <li><a href="https://www.uwo.ca/campusrec/" {ext}>News</a></li>
    <li><a href="https://www.uwo.ca/campusrec/" {ext}>Orientation</a></li>
    <li class="on"><a href="index.html">Schedules</a></li>
    <li><a href="https://www.uwo.ca/campusrec/" {ext}>Memberships</a></li>
    <li><a href="https://www.uwo.ca/campusrec/" {ext}>Programs</a></li>
    <li><a href="https://www.uwo.ca/campusrec/" {ext}>Intramurals</a></li>
    <li><a href="https://www.uwo.ca/campusrec/" {ext}>Sport Clubs</a></li>
    <li><a href="https://www.uwo.ca/campusrec/" {ext}>About</a></li>
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what the Campus Recreation pool schedule would
    look like as a live calendar. Not affiliated with Western University.</p>
    <p>Schedule transcribed 23 September 2026 from the Pool Lane Swim/Aquatics and Reading Week sections of
    the <a href="{SCHED}" {ext}>Western Campus Recreation Schedules/Hours page</a>. Calendars by
    <a href="https://www.poolrelay.com" {ext}>Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


QUESTIONS = """<section class="wrap">
  <h2>Questions for Campus Recreation Aquatics</h2>
  <p>Everything here was transcribed from the Schedules/Hours page. These are the places where it goes
  quiet or where we had to make a call &mdash; each one is also written on the calendar entry itself.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag gap">Gap</span>Does Fit Lane Swim run during Reading Week?</div>
      <div class="a">The building keeps adjusted hours October 13&ndash;16, and the pool section doesn't
      say whether its sessions change. The calendar shows the normal week.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Which tank is the 2SLGBTQIA+ swim in?</div>
      <div class="a">The other Saturday swims are marked (S). The 2SLGBTQIA+ swim, 12:00&ndash;1:00, has no
      tank code, so we put it in the shallow tank beside them.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>How many lanes in each tank?</div>
      <div class="a">The schedule names tanks, not lanes. With lane counts, each Fit Lane block could show
      how many lanes are open &mdash; and Tuesday and Thursday's &ldquo;S/D&rdquo; sessions how many in each.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>What happens in the December exam period?</div>
      <div class="a">The building has exam hours; the pool section says only that its hours change for Western
      holidays. Say which sessions move and the calendar shows them on their dates.</div>
    </li>
  </ul>
</section>

"""

POOL = f"""<section class="wrap hero">
  <div class="crumb">Home &raquo; Schedules</div>
  <h1>Pool Schedule</h1>
  <p class="kicker">Fit Lane Swim September 5 &ndash; December 23 &middot; community swims from September 19</p>
  <p class="lead">Everything in the Western Student Recreation Centre pool, a week at a time. Each block
  shows which layout the pool is in &mdash; <strong>SC</strong>, the 25 m short course, or
  <strong>LC</strong>, the 50 m long course &mdash; and which tank.</p>

{cal("pool", "Western WSRC Pool — this week", "Page ahead to October 12 to see Thanksgiving.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The codes, decoded once</h2>
    <p>Today the pool schedule is a table of times with a letter after each: (S), (D), (S/D), (LC), and a key
    beneath it. Two sentences above it explain that the lanes are 25 m on most days and 50 m on Fridays, and a
    note below it that the Saturday swims start September 19. Thanksgiving is in a different table, the
    Reading Week building hours.</p>
    <p class="answer">On the calendar every block already says it: <b>&ldquo;SC · Shallow&rdquo;, &ldquo;SC ·
    Shallow · Deep&rdquo;, &ldquo;LC&rdquo;</b>. The Saturday swims begin on September 19, and October 12
    simply shows the pool closed.</p>
  </div>
</div>

{QUESTIONS}"""

FIT = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Schedules</a> &raquo; Fit Lane Swim</div>
  <h1>Fit Lane Swim</h1>
  <p class="kicker">25 m short course Saturday&ndash;Thursday &middot; 50 m long course Fridays</p>
  <p class="lead">Mornings 6:45&ndash;9:00 and middays 11:00&ndash;2:00 Monday to Friday; evenings 4:00&ndash;6:00
  Monday and 4:00&ndash;7:00 Tuesday, Thursday and Friday; Saturday 1:00&ndash;4:00 and Sunday
  9:30&ndash;12:30. No evening session on Wednesday.</p>

{cal("fit", "Western Fit Lane Swim — the lane swim week", "Friday's three sessions are in the 50 m pool.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Long course, on the day it happens</h2>
    <p>A swimmer training for a 50 m meet wants to know one thing: when is the pool long course? The answer
    is a sentence above the table and an (LC) after each Friday time.</p>
    <p class="answer">On the calendar <b>Friday is the long-course day</b>, and every session says so, week
    after week through December 23.</p>
  </div>
</div>

{QUESTIONS}"""

COMMUNITY = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Schedules</a> &raquo; Rec &amp; Community Swims</div>
  <h1>Recreation &amp; Community Swims</h1>
  <p class="kicker">Saturdays from September 19 &middot; shallow tank</p>
  <p class="lead">Recreation Swim 9:30&ndash;10:45, Women's Only Swim 11:00&ndash;12:00 and 2SLGBTQIA+
  Swim 12:00&ndash;1:00, every Saturday from September 19 through the fall term.</p>

{cal("community", "Western Rec & Community Swims — Saturdays", "Page back to September 12 and they haven't started yet.")}
</section>

<section class="wrap">
  <div class="note">
    <span class="hd">Starting dates belong on the calendar</span>
    The published schedule lists these swims every Saturday, with a note underneath that they begin
    September 19. Here they begin on September 19, so nobody arrives on the 12th.
  </div>
</section>

{QUESTIONS}"""

PAGES = [
    ("index.html", "Pool Schedule &mdash; Western Campus Recreation (Pool Relay preview)",
     "Unofficial preview of the Western Campus Recreation pool schedule as a live Pool Relay calendar.", POOL),
    ("fit-lane-swim.html", "Fit Lane Swim &mdash; Western Campus Recreation (Pool Relay preview)",
     "Unofficial preview: Western Fit Lane Swim, with the 25 m and 50 m days on the calendar.", FIT),
    ("community-swims.html", "Rec &amp; Community Swims &mdash; Western Campus Recreation (Pool Relay preview)",
     "Unofficial preview: Western's Saturday recreation, Women's Only and 2SLGBTQIA+ swims.", COMMUNITY),
]

if __name__ == "__main__":
    for slug, title, description, body in PAGES:
        html = shell(slug, title, description, body)
        with io.open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(html)
        print(f"wrote {slug} ({len(html.encode()):,} bytes)")
